[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lui"
version = "0.1"
description = "Lui is a declarative language for creating user interfaces in Python"
authors = [
    {name = "Sergey", email = "pmswga@gmail.com"}
]

[project.urls]
homepage = "https://github.com/pmsgwa/lui"

[tool.bandit]
exclude_dirs = ["tests","examples", "venv", ".venv"]
